import type { Metadata } from "next";
import "./fonts.css";
import "./globals.css";


import NavbarWrapper from "@/components/layout/navbar/navbar-wrapper";
import Footer from "@/components/layout/footer";
import { CartProvider } from "@/components/cart/cart-context";
import { cookies } from "next/headers";
import { getCart } from "@/lib/shopify";
import PagePaddingWrapper from "@/components/layout/page-padding-wrapper";

export const metadata: Metadata = {
  title: "Anomie",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies();

  const cartId = cookieStore.get("cartId")?.value;
  const country = cookieStore.get("country")?.value || "US";

  const cartPromise = getCart(cartId, country);

  return (
    <html lang="en">
      <head>
        {/* Klaviyo Init */}
        <script
          dangerouslySetInnerHTML={{
            __html: `window._klOnsite = window._klOnsite || [];`,
          }}
        />

        {/* Klaviyo Loader (Same as Fear of God) */}
        <script 
          async 
          src="https://static.klaviyo.com/onsite/js/klaviyo.js?company_id=TcNjQk"
        ></script>
      </head>

      <body className="overflow-x-hidden">
        <CartProvider cartPromise={cartPromise} country={country}>
          <NavbarWrapper />
          <PagePaddingWrapper>{children}</PagePaddingWrapper>
         
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
